services:
  - type: web
    name: diverse-mind-library
    runtime: python
    buildCommand: bash build.sh
    startCommand: bash deploy.sh
    envVars:
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: diverse-mind.onrender.com
      - key: CONTENT_ADMIN_USERNAME
        value: admin
      - key: CONTENT_ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
